force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>fdsuihfgiuwhfiauwh</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>The referecned account is not the same as the account referenced by the opportunity. Please fix.</errorMessage>
        <filterItems>
            <field>Account.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Opportunity__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/invoicecontroller.cls
public with sharing class invoicecontroller {

    private Id oId;
    private Opportunity opp;
    public Decimal oppValue {get;set;}

    public InvoiceController(ApexPages.StandardSetController ssc) {
        oId = ApexPages.currentPage().getParameters().get('Id');
        loadOpportunity();
    }

    private void loadOpportunity(){
        opp = [SELECT Amount,AccountId FROM Opportunity WHERE ID = :oId];
        oppValue = opp.Amount;
    }

    public List<Invoice__c> newInvoices {
        get{
            if(newInvoices == null){
                newInvoices = new List<Invoice__c>();
                for (Integer i=0; i < 12; i++){
                    Invoice__c inv = new Invoice__c();
                        inv.Opportunity__c = oId;
                        inv.Account__c = opp.AccountId;
                        newInvoices.add(inv);
                }
            }
            return newinvoices;
        }
        set{}
    }

    public PageReference cancel(){
        Pagereference pr = new PageReference('/'+oid);
        return pr;
    }

    public PageReference save(){
        List<Invoice__c> invoicesToCreate = new List<Invoice__c>();

        for (Invoice__c inv : newInvoices){
            if(inv.Amount__c > 0){
                invoicesToCreate.add(inv);
            }
        }
        insert invoicesToCreate;


        Pagereference pr = new PageReference('/'+oid);
        return pr;
    }
}